
baseURL = "https://edithwuly.github.io"
languageCode = "zh-Hans"
title = "Edith Wu's Blog"
theme = "github.com/rudeigerc/yggdrasill"
copyright = "© 2023 Edith Wu. This site is licensed under a Creative Commons Attribution 4.0 International license."

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = true
paginate = 5

[author]
name = "Edith Wu"
email = "edithwuly@163.com"

[menu]

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts"
  weight = 2

[[menu.main]]
  name = "Catagories"
  url = "/categories"
  weight = 3

[markup]
[markup.highlight]
style = "github"
[markup.goldmark.renderer]
unsafe = true

[params]
subtitle = "@edithwuly"
description = "Edith Wu's Blog"
logo = "img/icon.svg"

[[params.social]]
  name = "GitHub"
  url = "https://github.com/edithwuly"
  type = "brands"
  icon = "github"

[[params.social]]
  name = "RSS"
  url = "/index.xml"
  type = "solid"
  icon = "rss"

[module]
[[module.imports]]
  path = "github.com/rudeigerc/yggdrasill"
